name: Maven Build

on:
  workflow_dispatch:
    inputs:
      dev:
        type: boolean
        description: dev
        required: false
        default: false

  workflow_call:
    outputs:
      branch_name:
        description: "Branch Name"
        value: ${{ jobs.Extract_Branch.outputs.branchname }}

jobs:
  Extract_Branch:
    runs-on: ubuntu-latest
    outputs:
      branchname: ${{ steps.extract_branch.outputs.branch}} 

    steps:
      - name: Extract Branch Name
        shell: bash  
        run: echo ##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

