name: CI

on:
  workflow_dispatch:
    inputs:
      javaversion:
        required: true
        type: number
  
jobs:
  Extract_Branch:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Branch Name
        shell: bash  
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '$ {{ github.event.inputs.javaversion }}'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -DskipTests clean package
