name: Maven Build

on:
  workflow_dispatch:

  workflow_call:
    outputs:
      branch_name:
        description: "Branch Name"
        value: ${{ jobs.Extract_Branch.outputs.branchname }}
    inputs:
      javaversion:
        required: true
        type: number
jobs:
  Extract_Branch:
    runs-on: ubuntu-latest
    outputs:
      branchname: ${{ steps.extract_branch.outputs.branch}} 

    steps:
      - name: Extract Branch Name
        shell: bash  
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
      - uses: actions/checkout@v3

      - name: Set up JDK '${{ inputs.javaversion }}'

        uses: actions/setup-java@v3
        with:
          java-version: '${{ inputs.javaversion }}'

      - name: Maven Build
        run: mvn -B package --file pom.xml
